# Generated by Django 6.0.1 on 2026-01-28 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('12L_IF2000', '12 litros IF-2.000 / 02 unidades gelox ice foam 2.000'), ('12L_IT1050', '12 litros IT-1050 / 03 unidades gelox ita fria 1050'), ('33L_IF1050', '33 litros IF-1050 PRECAUÇÃO / 01 unidade gelox Ice Foam-1050'), ('44L_IT1050', '44 litros IT-1050 / 06 unidades gelox Ita Fria 1050'), ('80L_IT1050', '80 litros IT-1050 / 10 unidades gelox Ita Fria 1050'), ('120L_IT1050', '120 litros IT-1050 / 12 unidades gelox Ita Fria 1050')], max_length=20, unique=True)),
                ('litros', models.IntegerField()),
                ('unidades_gelox', models.IntegerField()),
                ('tipo_gelox', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Modelo de Caixa',
                'verbose_name_plural': 'Modelos de Caixas',
            },
        ),
        migrations.CreateModel(
            name='TrocaGelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_caixa', models.CharField(choices=[('12L_IF2000', '12 litros IF-2.000 / 02 unidades gelox ice foam 2.000'), ('12L_IT1050', '12 litros IT-1050 / 03 unidades gelox ita fria 1050'), ('33L_IF1050', '33 litros IF-1050 PRECAUÇÃO / 01 unidade gelox Ice Foam-1050'), ('44L_IT1050', '44 litros IT-1050 / 06 unidades gelox Ita Fria 1050'), ('80L_IT1050', '80 litros IT-1050 / 10 unidades gelox Ita Fria 1050'), ('120L_IT1050', '120 litros IT-1050 / 12 unidades gelox Ita Fria 1050')], max_length=20, verbose_name='Modelo da Caixa')),
                ('numero_pedido', models.CharField(max_length=50, verbose_name='Número do Pedido da Caixa')),
                ('data_embalagem', models.DateField(verbose_name='Data da Embalagem da Caixa')),
                ('foto_etiqueta', models.ImageField(upload_to='trocas_gelo/etiquetas/%Y/%m/%d/', verbose_name='Foto da Etiqueta da Caixa')),
                ('foto_temperatura_medicamento', models.ImageField(upload_to='trocas_gelo/temp_medicamento/%Y/%m/%d/', verbose_name='Foto da Temperatura do Medicamento')),
                ('temperatura_medicamento', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='Temperatura do Medicamento (°C)')),
                ('foto_temperatura_gelo', models.ImageField(upload_to='trocas_gelo/temp_gelo/%Y/%m/%d/', verbose_name='Foto da Temperatura do Gelo')),
                ('temperatura_gelo', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='Temperatura do Gelo (°C)')),
                ('hora_finalizacao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Finalização')),
                ('hora_inicio_ambientacao', models.DateTimeField(editable=False, verbose_name='Início da Ambientação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Troca de Gelo 5S',
                'verbose_name_plural': 'Trocas de Gelo 5S',
                'ordering': ['-criado_em'],
            },
        ),
    ]
